### ISSUE TITLE
getCursor has unexpected behavior if null value in the path

### ISSUE THREAD

**Issue by clifton** [caseywebdev/cursors#2]
`getCursor` seems to have unexpected behavior if given a falsey value in the path.

From the demo below:

```html
<!doctype html>
<html>
  <head>
    <title>Falsey Path Test</title>
    <script src='bower_components/react/react-with-addons.js'></script>
    <script src='cursors.js'></script>
  </head>

  <body>
    <script>
      'use strict';

      var Foo = React.createFactory(React.createClass({
        mixins: [Cursors],

        render: function () {
          var myState = 'State: ' + JSON.stringify(this.state.foo);
          return React.createElement('div', null, myState);
        }
      }));

      var PathTest = React.createFactory(React.createClass({
        mixins: [Cursors],

        getInitialState: function () {
          return {
            fooId: null,
            fooCache: {123: {name: 'Bob', _id: 123}}
          };
        },

        handleChange: function (ev) {
          var val = ev.target.value || void 0;
          this.update({fooId: {$set: val}});
        },

        render: function () {
          return (
            React.createElement('div', null,
              React.createElement('input', {
                onChange: this.handleChange,
                value: this.state.fooId
              }),
              Foo({cursors: {foo: this.getCursor('fooCache', this.state.fooId)}})
            )
          );
        }
      }));

      document.addEventListener('DOMContentLoaded', function () {
        React.render(PathTest(), document.body);
      });
    </script>
  </body>
</html>
```

Whenever the input is empty, Foo gets into an unexpected state.

**Comment by caseywebdev** [comment]
I don't really think a `null` path can be valid. In your example, you're trying to render a `Foo` without even having a `fooId`. That's like an `<AccountShow accountId={null} />`. I think in your example a better design would be to not render `Foo` until you at least have a `fooId` to work with. Either that, or explicitly pass a "null" path by using something like `'' + this.state.foodId`, but that seems gross.

**Comment by clifton** [comment]
Right. I fixed it with `this.state.fooId || ''` but it doesn't *feel* right. I suppose `this.state.fooId && Foo({...})` would also be reasonable for not rendering Foo, but what if Foo has a blank slate?

I do think when retrieving state, it should stop at null/undefined when walking down the path, but returning the entire root object doesn't seem like the right thing to do.

**Comment by caseywebdev** [comment]
The path argument should be a string, number, or array of strings/numbers. Nothing else makes sense as nothing else can be an object key in JavaScript. I'll add that info to the README.

**Comment by clifton** [comment]
:+1:
